Template Helm Charts

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -21,6 +21,9 @@ jobs:
       - name: Install Helm
         run: |
           curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
+      
+      - name: Install JQ
+        run: sudo apt-get install -y jq
 
       - name: Configure Git
         run: |
@@ -89,24 +92,33 @@ jobs:
           
       - name: Upload Helm Chart Packages to GitHub Release
         if: github.ref == 'refs/heads/main'
+        env:
+          API_TOKEN: ${{ secrets.API_TOKEN }}
         run: |
-            # Extract the raw upload URL
-            upload_url="${{ steps.create_release.outputs.upload_url }}"
-            echo "Raw upload URL: $upload_url"
+            # Fetch the latest release information
+            latest_release=$(curl -s -H "Authorization: token $API_TOKEN" \
+              https://api.github.com/repos/${{ github.repository }}/releases/latest)
         
-            # Remove the placeholder from the upload URL
-            upload_url_clean=$(echo "$upload_url" | sed 's/{.*}//')
-            echo "Cleaned upload URL: $upload_url_clean"
+            # Extract the upload URL for assets (remove the placeholder)
+            upload_url=$(echo "$latest_release" | jq -r '.upload_url' | sed 's/{.*}//')
+            echo "Upload URL: $upload_url"
+        
+            # Check if the upload URL is valid
+            if [ -z "$upload_url" ]; then
+              echo "Failed to retrieve upload URL from the latest release."
+              exit 1
+            fi
         
             # Loop through packaged files and upload each
             for chart in ./packaged/*.tgz; do
               name=$(basename "$chart")
-              echo "Uploading $name to $upload_url_clean"
+              echo "Uploading $name to $upload_url"
               curl -X POST \
-                -H "Authorization: token ${{ secrets.API_TOKEN }}" \
+                -H "Authorization: token $API_TOKEN" \
                 -H "Content-Type: application/gzip" \
                 --data-binary @"$chart" \
-                "$upload_url_clean?name=$name"
+                "$upload_url?name=$name"
             done
+        
         
         
